AWSTemplateFormatVersion: "2010-09-09"
Description: "permission boundary"

Parameters:
  EngineerName1:
    Description: エンジニア1名前
    Type: String

Resources:
  Engineer1Password:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        GenerateStringKey: password
        PasswordLength: 16
        SecretStringTemplate: "{}"

  Engineer1:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref EngineerName1
      Path: "/"
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:${Engineer1Password}:SecretString:password::}}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      PermissionsBoundary: arn:aws:iam::aws:policy/PowerUserAccess
