AWSTemplateFormatVersion: "2010-09-09"
Description: "stack casestudy-iam-role"

Parameters:
  KeyPair:
    Description: Cfn作成・更新時にキーペアを入力してください。
    Type: "AWS::EC2::KeyPair::KeyName"

  AllowIP:
    Description: アクセスを許可するIPをCfn更新・作成時に入力してください
    Type: String

Resources:
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: casestudy-iam-role-sg
      GroupDescription: Allow SSHOnly
      VpcId: "vpc-06c1c9197507c6faa" #すぐ消すのですでにあったデフォルトVPCをハードコーディング
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowIP #スタック作成・更新時に入力されたIPを許可

  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0506f0f56e3a057a4 #無料利用枠 AmazonLinux2023
      KeyName: !Ref KeyPair # スタックの作成・更新時に入力されたキーペアを設定する
      InstanceType: t2.micro #無料利用枠
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref EC2SG
      Tags:
        - Key: Name
          Value: Batch-S3
      IamInstanceProfile: !Ref S3AccessInstanceProfile

  #S3のフルアクセスポリシー
  S3AccessPolicy:
    Description: "S3Accessロールの許可ポリシーとして使用"
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: S3Access
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
            Resource: "*"
      Roles:
        - !Ref S3AccessRole

  # EC2インスタンスに付与するロールを作成
  S3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3Access
      AssumeRolePolicyDocument: # 信頼ポリシーのこと
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - ec2.amazonaws.com #ec2
      Path: "/"

  # EC2インスタンスとロールを紐つけるためのプロファイル
  S3AccessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref S3AccessRole
