AWSTemplateFormatVersion: "2010-09-09"
Description: "casestudy-iam"
Resources:
  ApplicationGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "Application"

  ApplicationPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: Application
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ec2:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "elasticloadbalancing:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "autoscaling-plans:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "autoscaling-plans:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "rds:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "s3:*"
            Resource: "*"
      Groups:
        - !Ref ApplicationGroup
